### ISSUE TITLE
11. Pascal - Yield

### ISSUE THREAD

**Issue by ghost** [adebayo-dealdey/RubyTrack#11]
Print Pascal's triangle using 'yield'.Eg: pascal(6) gives:1 1 1 1 2 1 1 3 3 1 1 4 6 4 1 1 5 10 10 5 1 1 6 15 20 15 6 1

https://github.com/adebayo-dealdey/RubyTrack/tree/master/Pascal

**Comment by segunadeleye** [comment]
- For `process_yield_pascal_triangle`, use proper method names. You don't need to have yield within the method name because you are implementing yield.
- Use `do end` for multi-line blocks
- Why use `clone`?
- https://github.com/adebayo-dealdey/RubyTrack/blob/master/Pascal/bin/main.rb#L3 : How about using double quotes
- https://github.com/adebayo-dealdey/RubyTrack/blob/master/Pascal/bin/main.rb#L5 : How about using `p y` instead of puts `y.inspect`.
- https://github.com/adebayo-dealdey/RubyTrack/blob/master/Pascal/lib/integer.rb#L21 : Use array literal

**Comment by ghost** [comment]
Done all. Thanks.

**Comment by segunadeleye** [comment]
Looks good
